# Generated by Django 5.2 on 2025-04-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='renewed_times',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
