# Generated by Django 5.2 on 2025-04-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_borrowrecord_renewed_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='rental_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
