# Generated by Django 5.2 on 2025-04-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowrecord_rental_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='rental_days',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='rental_seconds',
            field=models.PositiveIntegerField(default=604800),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
