# Generated by Django 5.2 on 2025-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_borrowrecord_rental_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
