# Generated by Django 5.2 on 2025-04-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_member_total_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fine_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
